### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by darthf1** [auth0/jwt-auth-bundle#86]
Hi,

Can you tag a new release? With the current stable i'm unable to upgrade Symfony:

```
472 !!  PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /srv/api/vendor/auth0/jwt-auth-bundle/src/DependencyInjection/Configuration.php on line 20 and at least 1 expected in /srv/api/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
473 !!  Stack trace:
474 !!  #0 /srv/api/vendor/auth0/jwt-auth-bundle/src/DependencyInjection/Configuration.php(20): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
475 !!  #1 /srv/api/vendor/symfony/config/Definition/Processor.php(50): Auth0\JWTAuthBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
476 !!  #2 /srv/api/vendor/symfony/dependency-injection/Extension/Extension.php(106): Symfony\Component\Config\Definition\Processor->processConfiguration()
477 !!  #3 /srv/api/vendor/auth0/jwt-auth-bundle/src/DependencyInjection/JWTAuthExtension.php(19): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration()
478 !!  #4 /srv/api/vendor/symfony/dependency-injection/Compiler/Me in /srv/api/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
479 !!  
480 Script @auto-scripts was called via post-install-cmd
```

This is fixed in https://github.com/auth0/jwt-auth-bundle/pull/79

**Comment by joshcanhelp** [comment]
@darthf1 - Apologies for the delay here. I'll schedule this ASAP.

**Comment by joshcanhelp** [comment]
On its way!
